ISWM.WEB/Controllers/WardKaryakartaController.cs
using ISWM.WEB.BusinessServices;
using ISWM.WEB.BusinessServices.Repository;
using ISWM.WEB.BusinessServices.SingletonCS;
using ISWM.WEB.Common.CommonServices;
using ISWM.WEB.CommonCode;
using log4net;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ISWM.WEB.Controllers
{
    public class WardKaryakartaController : Controller
    {
        ILog log = log4net.LogManager.GetLogger(typeof(WardController));
        WardKaryakrtaRepository wkr = new WardKaryakrtaRepository();
        CommonCS cm = new CommonCS();
        GCommon gcm = new GCommon();
        // GET: WardKaryakarta

    /// <summary>
    /// This method is used to pass viewbag in listview for ward karyakarta
    /// coder:Smruti Wagh
    /// </summary>
    /// <returns></returns>
        public async Task<ActionResult> Index()
        {
            try
            {
                if (Session["User_id"] != null && Session["UserTypeID"] != null)
                {
                    if (Session["User_id"].ToString() == "0")
                    {
                        return RedirectToAction("Index", "Login");
                    }
                    else if ((Session["UserTypeID"].ToString() != "1" && Session["UserTypeID"].ToString() != "3"))
                    {
                        return RedirectToAction("Index", "Login");
                    }
                }
                else
                {
                    return RedirectToAction("Index", "Login");
                }


                var list =await wkr.GetViewWardkaryakartaList("desc", Convert.ToInt32(Session["User_id"]), Convert.ToInt32(Session["UserTypeID"]));
                ViewBag.WardkaryakartaList = list;
                if (TempData["MessageCode"] != null)
                {
                    ViewBag.MessageCode = TempData["MessageCode"];
                    if (ViewBag.MessageCode == 1)
                    {
                        ViewBag.MessageTxt = "Data updated successfully.";
                    }
                    else if (ViewBag.MessageCode == -1)
                    {
                        ViewBag.MessageTxt = "Data already available.";
                    }
                    else
                    {
                        ViewBag.MessageTxt = "Some error occurred while updating data.";
                    }
                    TempData["MessageCode"] = null;
                }
                else
                {
                    if (TempData["DeleteMessageCode"] != null)
                    {
                        ViewBag.MessageCode = TempData["DeleteMessageCode"];
                        if (ViewBag.MessageCode == 1)
                        {
                            ViewBag.MessageTxt = "Data Activate Successfully.";
                        }
                        else if (ViewBag.MessageCode == 2)
                        {
                            ViewBag.MessageCode = 1;
                            ViewBag.MessageTxt = "Data Inactivate Successfully.";
                        }
                        else
                        {
                            ViewBag.MessageTxt = "Some error occurred while deleting data.";
                        }
                        TempData["DeleteMessageCode"] = null;
                    }
                    else
                    {
                        ViewBag.MessageCode = null;
                    }
                }
                return View();
            }
            catch (Exception er)
            {
                log.Error("Error: " + er.Message);
                ViewBag.WardkaryakartaList = null;
                return View();
                //  throw;
            }
        }
        /// <summary>
        /// This method used to perform Insert Updte Delete operations is 0 it performs insert operation else perform modify operation
        /// coder: Smruti Wagh
        /// </summary>
        /// <param name="obj"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> Index(ward_Karyakrta_master obj)
        {
            try
            {

                obj.modified_by = Convert.ToInt32(Session["User_id"]);
                obj.modified_datetime = DateTime.Now;
                if (obj.id > 0)
                {
                    // TODO: Update insert logic here
                    int isUpdate =await wkr.ModifyWardkaryakarta(obj);
                    TempData["MessageCode"] = isUpdate;
                    return View();
                }
                else
                {

                    // TODO: Add insert logic here
                    obj.created_by = Convert.ToInt32(Session["User_id"]);
                    obj.created_datetime = DateTime.Now;
                    int isadd =await wkr.AddWardKaryakarta(obj);
                    TempData["MessageCode"] = isadd;
                    return View();
                }
            }
            catch (Exception er)
            {
                log.Error("Error: " + er.Message);
                return View();
                //  throw;
            }

        }

        /// <summary>
        /// This method is use to show partial view for add and edit information for ward karyakarta 
        /// coder: Smruti Wagh
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<ActionResult> AddEditModel(int id)
        {
            try
            {
                List<SelectListItem> list = new List<SelectListItem>();
                //for Status dropdown              
                list =await cm.GetStatusDDL();
                ViewBag.DDLStatus = list;
                //for ward drpdown               
                list = await cm.GetWardDDL(1);
                ViewBag.DDLWard = list;
                //for Area Dropdown
                list = await cm.GetAreaDDL(1);
                ViewBag.DDLArea = list;
                //for Karyakarta Dropdown
                list = await cm.GetUserDDL(6);
                ViewBag.DDLuser = list;
                var obj =await wkr.GetWardkaryakartaByID(id);
                return PartialView("AddEditModel", obj);

            }
            catch (Exception er)
            {
                log.Error("Error: " + er.Message);
                return RedirectToAction("Index");
            }
        }


        // GET: Ward/Delete/5
        public async Task<ActionResult> Delete(int id, int status)
        {

            try
            {
                ward_Karyakrta_master obj = new ward_Karyakrta_master();
                obj.id = id;
                obj.status = status;
                obj.modified_by = Convert.ToInt32(Session["User_id"]);
                obj.modified_datetime = DateTime.Now;
                int isdeleted =await wkr.DeleteWardkaryakarta(obj);
                TempData["DeleteMessageCode"] = isdeleted;
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                log.Error("Error " + ex.Message);
                return RedirectToAction("Index");
            }
        }


    }
}

ISWM.WEB/Views/WardKaryakarta/AddEditModel.cshtml
@model ISWM.WEB.BusinessServices.ward_Karyakrta_master

<!-->coder:Smruti Wagh
ward karykarta partial view for add and update-->

<div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title" id="add_new_institute_type">Add / Update Ward karykarta Information</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    <div class="modal-body">

        <!--begin::Form-->

<form class="kt-form" id="myForm">
    @Html.HiddenFor(model => model.id)
    <div class="form-group row">
        <div class="col-sm-12">
            <label class="col-form-label">Ward<span class="kt-font-danger">*</span></label>
            @Html.DropDownListFor(model => model.ward_id, new SelectList((System.Collections.IEnumerable)ViewBag.DDLWard, "Value", "Text"), "select", new { @class = "form-control", @required = "Required" })
        </div>
        <div class="col-sm-12">
            <label class="col-form-label">Area<span class="kt-font-danger">*</span></label>
            @Html.DropDownListFor(model => model.area_id, new SelectList((System.Collections.IEnumerable)ViewBag.DDLArea, "Value", "Text"), "select", new { @class = "form-control", @required = "Required" })
        </div>
        <div class="col-sm-12">
            <label class="col-form-label">Karyakarta <span class="kt-font-danger">*</span></label>
            @Html.DropDownListFor(model => model.karyakarta_id, new SelectList((System.Collections.IEnumerable)ViewBag.DDLuser, "Value", "Text"), "select", new { @class = "form-control", @required = "Required" })
        </div>
        <div class="col-sm-6">
            <label class="col-form-label">Status<span class="kt-font-danger">*</span></label>
            @Html.DropDownListFor(model => model.status, new SelectList((System.Collections.IEnumerable)ViewBag.DDLStatus, "Value", "Text"), "-- select --", new { @class = "form-control", @required = "Required" })
        </div>
    </div>
</form>
<!--end::Form-->
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" onclick="$('#add_new_info').modal('hide');$('#toast_error').toast('show');">Close</button>
        <button type="button" class="btn btn-primary" id="btnSubmit">Save Info</button>
    </div>

</div>

<script>

    $(document).ready(function () {

        $("#btnSubmit").click(function () {
            if ($("#myForm").valid()) {
        
                var myformdata = $("#myForm").serialize();

                $.ajax({

                    type: "POST",
                    url: "/WardKaryakarta/Index",
                    data: myformdata,
                    success: function () {
                        // $("#loaderDiv").hide();
                        $("#add_new_info").modal("hide");

                        window.location.href = "/WardKaryakarta/Index";

                    }

                });
            }
            else {
                return false;
            }
        })

    })


</script>

ISWM.WEB/Views/WardKaryakarta/Index.cshtml
@model ISWM.WEB.BusinessServices.ward_Karyakrta_master
<!--coder:Smruti Wagh
Ward karyakarta Index view to show data table-->
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="kt-content kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content">
    <!-- begin:: Subheader -->
    <div class="kt-subheader kt-grid__item" id="kt_subheader">
        <div class="kt-container kt-container--fluid kt-margin-t-10 kt-margin-b-10">

            <div class="kt-subheader__main">
                <h3 class="kt-subheader__title">Ward Karyakarta</h3>
            </div>
            <div class="kt-subheader__toolbar">
                <div class="kt-subheader__wrapper">
                    <a href="#" onclick="AddEditModel(0)" class="btn btn-icon- btn btn-label btn-label-primary btn-upper btn-font-sm btn-bold"><i class="fa fa-plus"></i> Add New</a>
                </div>
            </div>

        </div>
    </div>
    <!-- end:: Subheader -->
    <!-- begin:: Content -->
    <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">

        <div class="kt-portlet kt-portlet--mobile">
            <div class="kt-portlet__head">
                <div class="kt-portlet__head-label">
                    <h3 class="kt-portlet__head-title">Manage Ward Karyakarta Information</h3>
                </div>
            </div>
            <div class="kt-portlet__body">

                <!--begin: Datatable -->
                <table class="table table-striped- table-bordered table-hover table-checkable" id="kt_table_1">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Ward</th>
                            <th>Area</th>
                            <th>karyakarta</th>
                            <th>Contact No.</th>
                            <th>Status</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (ViewBag.WardkaryakartaList != null)
                        {
                            foreach (var item in ViewBag.WardkaryakartaList)
                            {
                        <tr>
                            <td>
                                @item.srno
                            </td>
                            <td>
                                @item.ward
                            </td>
                            <td>
                                @item.area
                            </td>
                            <td>
                                @item.karyakarta
                            </td>
                            <td>
                                @item.contact_no
                            </td>
                            <td>
                                <span class="badge @item.color_class kt-font-bold"> @item.status</span>

                            </td>

                            <td>
                                <a href="#" id="@item.id" onclick="AddEditModel(@item.id)" class="btn btn-sm btn-secondary btn-bold" title=""><span class="kt-font-primary">Edit</span></a>
                                
                                @if (item.status_id == 1)
                                {
                                    <a href="#" onclick="location.href='@Url.Action("Delete", "WardKaryakarta", new { id = item.id,status=2 })'" class="btn btn-sm btn-secondary btn-bold" title=""><span class="kt-font-danger">Mark Inactive</span></a>
                                }
                                else
                                {
                                    <a href="#" onclick="location.href='@Url.Action("Delete", "WardKaryakarta", new { id = item.id,status=1 })'" class="btn btn-sm btn-secondary btn-bold" title=""><span class="kt-font-success">Mark Active</span></a>
                                }
                            </td>
                        </tr>
                            }
                        }

                    </tbody>
                </table>
                <!--end: Datatable -->
            </div>
        </div>
    </div>
    <!-- end:: Content -->
</div>
<!-- Modal -->
<div class="modal fade" id="add_new_info" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable" role="document" id="myModalBodyDiv1">

    </div>
</div>

<script>

    var AddEditModel = function (id) {

        var url = "/WardKaryakarta/AddEditModel?id=" + id;

        $("#myModalBodyDiv1").load(url, function () {
            $("#add_new_info").modal("show");

        })

    }
</script>